services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: erp-app
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
      - ./storage:/var/www/html/storage
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=postgresql-pgb6-postgresql-1
      - DB_PORT=5432
      - DB_DATABASE=erp_pesantren
      - DB_USERNAME=pesantren
      - DB_PASSWORD=ASy-5Yifaa
    networks:
      - postgresql-pgb6_default

  nginx:
    image: nginx:alpine
    container_name: erp-nginx
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
      - ./storage:/var/www/html/storage
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.erp.rule=Host(`erp.asy-syifaa.com`) || Host(`api.asy-syifaa.com`)"
      - "traefik.http.routers.erp.entrypoints=websecure"
      - "traefik.http.routers.erp.tls.certresolver=letsencrypt"
      - "traefik.http.services.erp.loadbalancer.server.port=80"
    networks:
      - postgresql-pgb6_default

networks:
  postgresql-pgb6_default:
    external: true
